/*CREATE DATABASE ESCOLA;*/

/*CREATE TABLE ALUNOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(120) NOT NULL
);*/

/*SELECT ID, NOME FROM ALUNOS LIMIT 10;*/

/*INSERT INTO ALUNOS (NOME)
VALUES ('AGATHA'),('MIRELLA'),('VITOR')*/

/*ID ESPECIFICO*/
/*SELECT NOME FROM alunos WHERE ID = 1;*/

/*SELECT ID,NOME FROM alunos ORDER BY NOME ASC;*/

/*SELECT COUNT(*) AS TOTAL_ALUNOS FROM alunos;*/

/*COMEÇO DO NOME % DEPOIS */
/*SELECT * FROM alunos WHERE NOME LIKE "A%";*/

/*FINAL DO NOME % ANTES */
/*SELECT * FROM alunos WHERE NOME LIKE "%R";*/

/*DUAS ULTIMAS LETRAS DO NOME % DOIS LADOS */
/*SELECT * FROM alunos WHERE NOME LIKE "%LA%";*/

/*INSERT INTO alunos( NOME ) VALUES ('MIRELLA')*/

/*NÃO MOSTRA NOMES REPITIDOS*/
/*SELECT DISTINCT NOME FROM alunos;*/

/*CONTA OS NOMES AGRUPA E ORDENA POR ORDEM DECRESCENTE*/
/*SELECT NOME, COUNT(*) AS TOTAL FROM alunos
GROUP BY NOME ORDER BY TOTAL DESC;*/

/*CREATE TABLE CURSOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_CURSO VARCHAR(120) NOT NULL);*/

/*CREATE TABLE MATRICULAS (
ID INT AUTO_INCREMENT PRIMARY KEY,
ALUNO_ID INT, 
CURSO_ID INT,

FOREIGN KEY (ALUNO_ID) REFERENCES alunos(ID),
FOREIGN KEY (CURSO_ID) REFERENCES cursos(ID)
); */

/*SELECT * FROM matriculas;*/

/*INSERT INTO cursos (NOME_CURSO) VALUES 
('INFORMÁTICA'),
('ADMISNISTRAÇÃO'),
('METALURGIA'),
('MECATRONICA');*/


/*INSERT INTO matriculas (ALUNO_ID, CURSO_ID) VALUES
(1,1),
(2,1),
(3,2),
(1,2);*/

/*SELECT 
	ALUNOS.NOME AS ALUNO,
	cursos.NOME_CURSO AS CURSO
 
FROM matriculas
INNER JOIN alunos ON MATRICULAS.ALUNO_ID = alunos.ID
INNER JOIN cursos ON matriculas.CURSO_ID = cursos.ID;*/

/*DELETE FROM alunos WHERE ID = 4;*/









